let mc = midichan
    midicc num val = (# ccn num) . (# ccv val)
    -- ccEuclid cc divs pat = euclid (floor <$> (segment 1 $ range 1 divs $ cF 0 cc)) divs $ pat
    cceuc8 c p = euclid (floor <$> (segment 1 $ range 1 8 $ cF 0 c)) 8 $ p
    cceuc16 c p = euclid (floor <$> (segment 1 $ range 1 16 $ cF 0 c)) 16 $ p
    -- lcFader1 :: Pattern Double
    lcFader1 = cF 0 "77"
    -- lcFader2 :: Pattern Double
    lcFader2 = cF 0 "78"
    -- lcFader3 :: Pattern Double
    lcFader3 = cF 0 "79"
    -- lcFader4 :: Pattern Double
    lcFader4 = cF 0 "80"
    -- lcFader5 :: Pattern Double
    lcFader5 = cF 0 "81"
    -- lcFader6 :: Pattern Double
    lcFader6 = cF 0 "82"
    -- lcFader7 :: Pattern Double
    lcFader7 = cF 0 "83"
    -- lcFader8 :: Pattern Double
    lcFader8 = cF 0 "84"
    -- lcF1 :: Pattern Double
    lcF1 = cF 0 "77"
    -- lcF2 :: Pattern Double
    lcF2 = cF 0 "78"
    -- lcF3 :: Pattern Double
    lcF3 = cF 0 "79"
    -- lcF4 :: Pattern Double
    lcF4 = cF 0 "80"
    -- lcF5 :: Pattern Double
    lcF5 = cF 0 "81"
    -- lcF6 :: Pattern Double
    lcF6 = cF 0 "82"
    -- lcF7 :: Pattern Double
    lcF7 = cF 0 "83"
    -- lcF8 :: Pattern Double
    lcF8 = cF 0 "84"
    -- lcTopKnob1 :: Pattern Double
    lcTopKnob1 = cF 0 "13"
    -- lcTopKnob1 :: Pattern Double
    lcTopKnob2 = cF 0 "14"
    -- lcTopKnob3 :: Pattern Double
    lcTopKnob3 = cF 0 "15"
    -- lcTopKnob4 :: Pattern Double
    lcTopKnob4 = cF 0 "16"
    -- lcTopKnob5 :: Pattern Double
    lcTopKnob5 = cF 0 "17"
    -- lcTopKnob6 :: Pattern Double
    lcTopKnob6 = cF 0 "18"
    -- lcTopKnob7 :: Pattern Double
    lcTopKnob7 = cF 0 "19"
    -- lcTopKnob8 :: Pattern Double
    lcTopKnob8 = cF 0 "20"
    -- lcTK1 :: Pattern Double
    lcTK1 = cF 0 "13"
    -- lcTK2 :: Pattern Double
    lcTK2 = cF 0 "14"
    -- lcTK3 :: Pattern Double
    lcTK3 = cF 0 "15"
    -- lcTK4 :: Pattern Double
    lcTK4 = cF 0 "16"
    -- lcTK5 :: Pattern Double
    lcTK5 = cF 0 "17"
    -- lcTK6 :: Pattern Double
    lcTK6 = cF 0 "18"
    -- lcTK7 :: Pattern Double
    lcTK7 = cF 0 "19"
    -- lcTK8 :: Pattern Double
    lcTK8 = cF 0 "20"
    -- lcMidKnob1 :: Pattern Double
    lcMidKnob1 = cF 0 "29"
    -- lcMidKnob2 :: Pattern Double
    lcMidKnob2 = cF 0 "30"
    -- lcMidKnob3 :: Pattern Double
    lcMidKnob3 = cF 0 "31"
    -- lcMidKnob4 :: Pattern Double
    lcMidKnob4 = cF 0 "32"
    -- lcMidKnob5 :: Pattern Double
    lcMidKnob5 = cF 0 "33"
    -- lcMidKnob6 :: Pattern Double
    lcMidKnob6 = cF 0 "34"
    -- lcMidKnob7 :: Pattern Double
    lcMidKnob7 = cF 0 "35"
    -- lcMidKnob8 :: Pattern Double
    lcMidKnob8 = cF 0 "36"
    -- lcMK1 :: Pattern Double
    lcMK1 = cF 0 "29"
    -- lcMK2 :: Pattern Double
    lcMK2 = cF 0 "30"
    -- lcMK3 :: Pattern Double
    lcMK3 = cF 0 "31"
    -- lcMK4 :: Pattern Double
    lcMK4 = cF 0 "32"
    -- lcMK5 :: Pattern Double
    lcMK5 = cF 0 "33"
    -- lcMK6 :: Pattern Double
    lcMK6 = cF 0 "34"
    -- lcMK7 :: Pattern Double
    lcMK7 = cF 0 "35"
    -- lcMK8 :: Pattern Double
    lcMK8 = cF 0 "36"
    -- lcBottomKnob1 :: Pattern Double
    lcBottomKnob1 = cF 0 "49"
    -- lcBottomKnob2 :: Pattern Double
    lcBottomKnob2 = cF 0 "50"
    -- lcBottomKnob3 :: Pattern Double
    lcBottomKnob3 = cF 0 "51"
    -- lcBottomKnob4 :: Pattern Double
    lcBottomKnob4 = cF 0 "52"
    -- lcBottomKnob5 :: Pattern Double
    lcBottomKnob5 = cF 0 "53"
    -- lcBottomKnob6 :: Pattern Double
    lcBottomKnob6 = cF 0 "54"
    -- lcBottomKnob7 :: Pattern Double
    lcBottomKnob7 = cF 0 "55"
    -- lcBottomKnob8 :: Pattern Double
    lcBottomKnob8 = cF 0 "56"
    -- lcLowKnob1 :: Pattern Double
    lcLowKnob1 = cF 0 "49"
    -- lcLowKnob2 :: Pattern Double
    lcLowKnob2 = cF 0 "50"
    -- lcLowKnob3 :: Pattern Double
    lcLowKnob3 = cF 0 "51"
    -- lcLowKnob4 :: Pattern Double
    lcLowKnob4 = cF 0 "52"
    -- lcLowKnob5 :: Pattern Double
    lcLowKnob5 = cF 0 "53"
    -- lcLowKnob6 :: Pattern Double
    lcLowKnob6 = cF 0 "54"
    -- lcLowKnob7 :: Pattern Double
    lcLowKnob7 = cF 0 "55"
    -- lcLowKnob8 :: Pattern Double
    lcLowKnob8 = cF 0 "56"
    -- lcLK1 :: Pattern Double
    lcLK1 = cF 0 "49"
    -- lcLK2 :: Pattern Double
    lcLK2 = cF 0 "50"
    -- lcLK3 :: Pattern Double
    lcLK3 = cF 0 "51"
    -- lcLK4 :: Pattern Double
    lcLK4 = cF 0 "52"
    -- lcLK5 :: Pattern Double
    lcLK5 = cF 0 "53"
    -- lcLK6 :: Pattern Double
    lcLK6 = cF 0 "54"
    -- lcLK7 :: Pattern Double
    lcLK7 = cF 0 "55"
    -- lcLK8 :: Pattern Double
    lcLK8 = cF 0 "56"
    volRange = range 0.3 1.5